#!/usr/bin/env python3
import os
import sys
import sqlite3
import subprocess

def spawn_ssh(user, host, port=22):
	# https://bugs.python.org/issue/8557
	if sys.platform == "win32":
		system32 = os.path.join(os.environ['SystemRoot'], 'SysNative')
		ssh_path = os.path.join(system32, 'OpenSSH/ssh.exe')
	else :
		ssh_path = "ssh"
	p = subprocess.call([ssh_path, user + "@" + host, "-p", str(port)])

def create_sqlite3_db(db_name):
	conn = sqlite3.connect(db_name)
	c = conn.cursor()
	c.execute('''CREATE TABLE devices (device text, user text, ip text, port int)''')
	conn.commit()
	conn.close()

def update_sqlite3_db(db_name, sqlite3_data):
	conn = sqlite3.connect(db_name)
	c = conn.cursor()
	sqlite3_cmd = ("INSERT INTO devices VALUES ('{0}','{1}','{2}', '{3}')".format(data[0], data[1], data[2], data[3]))
	c.execute(sqlite3_cmd)
	conn.commit()
	conn.close()

def delete_device(db_name, device_name):
	conn = sqlite3.connect(db_name)
	c = conn.cursor()
	sqlite3_cmd = ("DELETE FROM devices WHERE device='{0}'".format(device_name))
	c.execute(sqlite3_cmd)
	conn.commit()
	conn.close()

def read_sqlite3_db(db_name, device_name=None):
	conn = sqlite3.connect(db_name)
	c = conn.cursor()
	user = None
	ip = None
	port = 0
	if device_name is None:
		cmd = c.execute("SELECT * FROM devices")
		for row in cmd:
			print("===============")
			print("name : %s" % row[0])
			print("user : %s" % row[1])
			print("ip   : %s" % row[2])
			print("port : %s" % row[3])
		print("===============")
		conn.close()
	else :
		cmd = c.execute("SELECT * FROM devices WHERE device='{0}'".format(device_name))
		for row in cmd:
			user = row[1]
			ip = row[2]
			port = row[3]
		conn.close()
		return user, ip, port

def usage(pyname):
	print("usage : %s [args]" % pyname)
	print(" -a, --add <device|username|ip|port>\tadd device to list")
	print(" -c, --connect [device]\t\t\tconnect to device")
	print(" -d, --delete [device]\t\t\tdelete device from list")
	print(" -l, --list\t\t\t\tlist devices")

if __name__ == '__main__':

	add = False
	list_dev = False
	connect_dev = False
	delete_dev = False

	argv = sys.argv
	argc = len(argv)

	data = list()
	if argc == 1:
		usage(argv[0])
	for i in range(0, argc):
		if argv[i] == "-a" or argv[i] == "--add":
			if argc != 6:
				print("not enough arg")
				sys.exit(-1)

			for j in range(2, 6):
				data.append(argv[j])
			add = True

		elif argv[i] == "-c" or argv[i] == "--connect":
			device = argv[i + 1]
			print("connect to device : %s" % device)
			connect_dev = True
		elif argv[i] == "-l" or argv[i] == "--list":
			list_dev = True
		elif argv[i] == "-d" or argv[i] == "--delete":
			device = argv[i + 1]
			delete_dev = True
		elif argv[i] == "-h" or argv[i] == "--help":
			usage(argv[0])

	if sys.platform == "win32":
		sqlite3_db = os.environ['HOMEPATH'] + "/remotepy.db"
	else:
		sqlite3_db = os.environ['HOME'] + "/remotepy.db"

	if add is True:
		if not os.path.isfile(sqlite3_db):
			create_sqlite3_db(sqlite3_db)
			update_sqlite3_db(sqlite3_db, data)
		else:
			if read_sqlite3_db(sqlite3_db, device_name=data[0])[0] != None:
				print("[ERROR] a device with name \"%s\" already exists" % data[0])
			else :
				update_sqlite3_db(sqlite3_db, data)

	if list_dev is True:
		read_sqlite3_db(sqlite3_db)

	if connect_dev is True:
		user, ip, port = read_sqlite3_db(sqlite3_db, device_name=device)
		spawn_ssh(user, ip, port)

	if delete_dev is True :
		if read_sqlite3_db(sqlite3_db, device_name=device)[0] == None:
			print("[ERROR] device with name \"%s\" does not exist" % device)
		else :
			delete_device(sqlite3_db, device)
			print("[INFO] deleted \"%s\"" % device)